### ISSUE TITLE
Research visual design needs for Marigold

### ISSUE THREAD

**Issue by juliasolorzano** [18F/marigold#30]
After talking with a few folks it is clear that we need to do some research around what our visual design folks need from Marigold. Adding this issue to start kicking this off with creating a research plan with an interview template for discovery work to happen.

- [x] Create overarching plan of how to approach the research
- [x] Create interview template
- [x] Do interviews!
- [x] Synthesize the research
- [x] Create actionable items
- [x] 💥

**Comment by juliasolorzano** [comment]
Referencing https://github.com/18F/marigold/issues/14

During a critique session @vz3 made the following recommendation in the issue referenced above. Adding here to include it as part of this research work.

**Comment by msecret** [comment]
Some ideas for research plan:
- Keep it open in what visual designs generally need from design systems, not just Marigold? I want to keep the research open enough that Marigold might not actually be the solution as teams might benefit more from individual style guides.
- Do designers want to prototype in code or in design software? How would they do so either way?
- Where does branch come into play in design process? Is it useful to work with unbranded components at some point?

**Comment by juliasolorzano** [comment]
Initial research plan started here: https://docs.google.com/document/d/111lPnFRyvAX_wk2XZzB2Z6dASp-OZT_zJAg_mPdUfEY/edit#

**Comment by juliasolorzano** [comment]
> I want to keep the research open enough that Marigold might not actually be the solution as teams might benefit more from individual style guides.

@msecret I could not agree more! I am super glad we are doing this research to figure out what is needed and build something that is beneficial for ourselves and our colleagues 🇺🇸

**Comment by juliasolorzano** [comment]
Asked team to review plan by EOD today and leave feedback. Looking at scheduling interviews over the coming two weeks.

**Comment by juliasolorzano** [comment]
Invites have been sent to all perspective interviewees and interviews are getting scheduled for the weeks of 1/9 and 1/16.

**Comment by juliasolorzano** [comment]
Interviews are now completed and located here:

https://drive.google.com/drive/folders/0B_NVRFrsefnvUU54Umhrc3VkRlU

Synthesis is scheduled for Monday, January 30th. We will be doing an [affinity diagramming](https://methods.18f.gov/decide/affinity-diagramming/) exercise to evaluate patterns and overarching themes.

**Comment by juliasolorzano** [comment]
@msecret removing you as assignee for now, but let me know if you are still interested in helping out!

**Comment by juliasolorzano** [comment]
This work is now completed.

Synthesis document is located here: https://docs.google.com/document/d/1lYXu35oivvZjEgXwxXjeTdxAhFtaLli7Ulr5sR6nrJ8/edit
