### ISSUE TITLE
Evaluate Fractal best practices/architecture

### ISSUE THREAD

**Issue by juliasolorzano** [18F/marigold#32]
This issue is for evaluating best practices for the Marigold code base. Here are a few bullet points to help guide the work in this issue:

- [x] Evaluate current project architecture of Marigold base to current Fractal guidelines
- [x] Create a task list of items to update, edit or remove
- [x] Open issue around these tasks with well defined guidelines for the work

**Comment by line47** [comment]
**Items to update**
- [x] Add component statuses (Hypothesis, Proposed, Alpha, Beta, Recommended, Deprecated)
- [x] Add document statuses (Alpha, Beta, Recommended)
- [x] Move status indicator in the navigation to the left of the component name (easier to scan)

**Items to add**
- [x] Setup USWDS styles centrally to avoid duplication
- [x] Setup USWDS images centrally to avoid duplication
- [x] Categorize and group components

**Comment by juliasolorzano** [comment]
@line47 these all look great - thanks Scott! I'll be opening some new issues to tackle these and then close this one once those are completed.

**Comment by juliasolorzano** [comment]
@line47 I added the above issues for us to get started on the work. Please feel free to self assign anything that you'd like to tackle!

Also, can you expand a bit more on the work you see as part of the `Categorize and group components` task?

**Comment by line47** [comment]
@juliaelman I think categorizing and grouping components will come when there are more components that are part of marigold. For example, 

- **Base** - Typography, colors, grid, labels
- **Components** - Button, table, alert
- **Forms** - Form elements, form controls, Form templates
- **Layouts** - Landing page, documentation page

**Comment by juliasolorzano** [comment]
New issues have been opened and all tasks are completed! Closing.
