### ISSUE TITLE
Update running locally with Fractal CLI installation instructions

### ISSUE THREAD

**Issue by line47** [18F/marigold#33]
Add information about installing Fractal CLI tool to the running locally installation instructions.
This was something that I nneded to setup bu didn't know because it was not documented.

### Proposed content to add

Fractal CLI tool, [installation instructions](http://fractal.build/guide/installation#installing-the-fractal-cli-tool) 

### Acceptance Criteria
- [x] Fractal CLI instructions are part of the marigold README

**Comment by juliasolorzano** [comment]
Fixed in #34
