### ISSUE TITLE
Research around writing Sketch plugins that translate HTML

### ISSUE THREAD

**Issue by juliasolorzano** [18F/marigold#54]

**Comment by juliasolorzano** [comment]
Update: @line47 has found a few and will be testing them out. Will share a list here.

**Comment by line47** [comment]
interesting sketch plugins I'm testing 

- https://github.com/sskyy/blade
- https://github.com/mamuso/sketch-designdoc 
- https://github.com/JohnCoates/CSSketch 
- https://github.com/turbobabr/sketch-devtools

**Comment by line47** [comment]
Right now [Blade](https://github.com/sskyy/blade) seems like it does some really cool stuff (conceptually) though it is a legacy plugin at the moment. I was going to look into how to bring it out of legacy and update it to be compatible with the most recent version of Sketch. (42)

**Comment by juliasolorzano** [comment]
@line47 awesome! What do you see Blade doing that sets it apart from the other tools you've been researching?

**Comment by line47** [comment]
@juliaelman using layer names such as [btn] or input[text]. that then create different types of dom elements.
